### ISSUE TITLE
Requiring CUDA10+ precludes running racon-gpu on the (current?) ONT PromethION

### ISSUE THREAD

**Issue by SamStudio8** [NVIDIA-Genomics-Research/racon-gpu#2]
A [recent change in the README](https://github.com/clara-genomics/racon-gpu/commit/7c181cfe1b95ea27ec5494d4ccfb95ae77e45c5e#diff-04c6e90faac2675aa89e2176d2eec7d8R27) specifies a requirement for CUDA10+, but this precludes `racon-gpu` being run on our ONT PromethION as the driver it ships with (v384.130) does not support the CUDA toolkit beyond v9.0 on Linux x86_64 ([doc](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html)).

With a little hacking I've managed to compile `racon-gpu` with CUDA 9.0.176 and run it on our PromethION, so I was wondering if this version constraint was intentional?

**Comment by tijyojwad** [comment]
@SamStudio8 latest release of racon-gpu works with CUDA 9.0. Can we close this issue?

**Comment by SamStudio8** [comment]
@tijyojwad Sounds good! Presumably this means we don't have to worry about the `pattern_formatter.h` now?

**Comment by tijyojwad** [comment]
@SamStudio8 That's right, no need to worry about `pattern_formatter.h` in CUDA 9.0 builds anymore
