### ISSUE TITLE
New repo for racon-gpu

### ISSUE THREAD

**Issue by tijyojwad** [NVIDIA-Genomics-Research/racon-gpu#5]
Hi @akkamesh @habibzadeh @SamStudio8 @shajoezhu @winterlich @yyht  - 

Due to upstream racon repo officially moving to a new location (https://github.com/lbcb-sci/racon), we have created a new fork for racon-gpu.

We noticed that you had previously forked from clara-genomics/racon-gpu. We have renamed that one to clara-genomics/racon-gpu-old, and clara-genomics/racon-gpu is now a fork of lbcb-sci/racon.

Please re-fork from this new repository to stay up to date with our developments, and thank you for the continued support and interest in our work!

**Comment by shajoezhu** [comment]
Many thanks @tijyojwad !

**Comment by tijyojwad** [comment]
Closing as devs who forked have been informed.
